---
json_rpc_url: https://api.devnet.solana.com
websocket_url: ''
keypair_path: dad2b6kvsopY92SPsRVheumPyQm4znurhevxCesu7We.json
address_labels:
  '11111111111111111111111111111111': System Program
commitment: confirmed
